version : "3"
services:
   stackweb:
      image: "nginx:latest"
      deploy:
         replicas: 5
         restart_policy:
            condition: on-failure
         resources:
           limits:
             cpus: "0.1"
             memory: 50M
      ports:
         - "8180:80"
      networks:
         - nginx-net
networks:
   nginx-net:

# docker stack deploy -c docker-compose.yaml nginxstack
