version: '3'
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      #- /tmp/db_data:/var/lib/mysql
      - mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8484:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wpsite_network
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8585:80'
    restart: always
    #volumes: ['/tmp/wp:/var/www/html']
    volumes: [wordpress_data:/var/www/html]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite_network
networks:
  wpsite_network:
volumes:
  mysql_db_data:
  wordpress_data:
############################################################
#docker-compose up
#docker-compose up -d
#docker-compose down
#docker system prune -a
#docker volume prune
#
#docker stack deploy -c docker-compose.yaml mysqlphpawp
############################################################


